stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - data/raw/bank_data.csv
      - src/preprocess.py
    outs:
      - data/processed/bank_data.csv

  train:
    cmd: python src/train.py ${threshold}
    deps:
      - data/processed/bank_data.csv
      - src/train.py
    outs:
      - models/ols_model.pkl
    metrics:
      - metrics/metrics.json:
          cache: false
    params:
      - threshold

  evaluate_rdd:
    cmd: python src/evaluate_rdd.py ${threshold} ${bandwidth}
    deps:
      - data/processed/bank_data.csv
      - src/evaluate_rdd.py
    params:
      - threshold
      - bandwidth
    metrics:
      - metrics/rdd_eval_t${threshold}_bw${bandwidth}.json:
          cache: false

  evaluate_roi:
    cmd: python src/evaluate_roi.py ${threshold} ${bandwidth} ${extra_recovery_cost}
    deps:
      - src/evaluate_roi.py
      - metrics/rdd_eval_t${threshold}_bw${bandwidth}.json
    params:
      - threshold
      - bandwidth
      - extra_recovery_cost
    metrics:
      - metrics/roi_t${threshold}_bw${bandwidth}.json:
          cache: false
